spring.application.name=E-Commerce
# Configuration de la base de données SQL Server avec authentification Windows
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=E_Commerce;integratedSecurity=true;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username= # Laissez vide si vous utilisez l'authentification Windows
spring.datasource.password= # Laissez vide si vous utilisez l'authentification Windows

# Configuration de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
